[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "About Us"
pageRef = "/about-us/"
weight = 20

[[main]]
name = "Concerts"
pageRef = "/concerts/"
weight = 30

[[main]]
name = "Ringers"
pageRef = "/ringers/"
weight = 40

[[main]]
name = "Repertoire"
pageRef = "/repertoire/"
weight = 50

[[main]]
name = "Audition"
pageRef = "/audition/"
weight = 60

[[main]]
name = "Contact"
pageRef = "/contact/"
weight = 70

[[main]]
name = "Support"
pageRef = "/support/"
weight = 80
