media:
  - name: images
    label: Main Images
    input: assets/images
    output: /images
  - name: ringers
    label: Ringer Photos
    input: assets/ringers
    output: /ringers
  - name: concerts
    label: Concert Logos and Posters
    input: assets/concerts
    output: /concerts
settings:
  commit:
    identity: user
  content:
    merge: true
content:
  - name: main
    label: Main Pages
    type: collection
    path: content
    subfolders: false
    operations:
      create: false
      delete: false
      rename: false
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
      - name: featured_image
        type: image
        options:
          media: images
          rename: safe
      - name: body
        type: rich-text
  - name: ringers
    label: Ringer Bios
    type: collection
    path: content/ringers
    exclude:
      - _index.md
    subfolders: false
    format: yaml-frontmatter
    view:
      fields: [first, last, director, sort, weight]
      sort: [first, last, sort, weight]
      default:
        sort: sort
        order: asc
      layout: list
    fields:
      - name: first
        label: First Name
        type: string
      - name: last
        label: Last Name
        type: string
      - name: director
        label: Director
        type: boolean
        default: false
      - name: sort
        label: Sort (by text)
        type: string
      - name: weight
        label: Sort (numeric)
        type: number
      - name: photo
        label: Ringer Photo
        type: image
        options:
          media: ringers
          rename: safe
      - name: body
        type: rich-text
  - name: locations
    label: Concert Locations
    type: collection
    path: content/locations
    format: yaml-frontmatter
    exclude:
      - _index.md
    fields:
      - name: title
        label: Display Name
        type: string
        required: true
      - name: image
        type: image
        options:
          media: images
          rename: safe
      - name: street
        label: Street Address
        type: string
        required: true
      - name: city
        label: City
        type: string
        required: true
      - name: state
        label: State
        type: string
        required: true
        maxlength: 2
      - name: short
        label: Short Unique Description
        type: string
        required: true
        description: City or Abbreviation
  - name: repertoire
    label: Repertoire Pieces
    type: collection
    path: content/repertoire
    exclude:
      - /_index.md
    filename:
      template: "{slug}/_index.md"
      field: true
    fields:
      - name: slug
        label: Piece ID
        type: string
        required: true
        description: Used for reference from concert
      - name: external
        label: External Group Piece
        type: boolean
        default: false
        required: false
        description: Indicate has not been performed by BotR (ie other ensemble in joint concert)
      - name: title
        label: Piece Title
        type: string
        required: true
      - name: composer
        label: Composer
        type: string
        list: true
        required: true
      - name: arranger
        label: Arranger
        type: string
        description: 'arr. '
        required: false
      - name: adapted
        label: Adapted BY
        type: string
        required: false
      - name: transcribed
        label: Transcribed By
        type: string
        required: false
      - name: body
        label: Extra Info
        type: rich-text
        options:
          media: images
          rename: safe
        required: false
        description: 'Lyrics, concert notes?'
  - name: concerts
    label: Concerts
    type: collection
    path: content/concerts
    exclude:
      - /_index.md
    view:
      fields: [year, season, extra, title]
      sort: [sort, title]
      default:
        sort: sort
        order: asc
      layout: list
    fields:
      - name: year
        label: Year
        type: number
        min: 1996
        max: 2100
        required: true
      - name: season
        label: Season/Month
        type: string
        required: true
      - name: poster
        label: Promotional Poster
        type: image
        options:
          media: concerts
          rename: safe
        required: false
      - name: logo
        label: Concert Logo
        type: image
        options:
          media: concerts
          rename: safe
        required: false
        description: Should be similar to poster, without text details
      - name: extra
        label: Extra Description
        description: 'Ex: Area 11 Festival. Usually blank'
        required: false
      - name: sort
        label: Sort String
        description: 'Should force to roughly time order (YYYY-MM)'
        type: string
        required: true
      - name: title
        label: Program Title
        type: string
        required: true
      - name: public_after
        label: Publish After
        type: date
        required: false
        options:
          time: true
        description: Use to delay when videos release. Will require rebuild.
      - name: dates
        label: Concert Dates
        type: object
        list:
          min: 1
          collapsible:
            collapsed: true
            summary: '({short}) {date} {time}'
        fields:
          - name: date
            type: date
            options:
              time: false
            required: true
          - name: time
            type: date
            options:
              time: true
              format: 'HH:mm'
              step: 5
            description: 'WOULD CHANGE IF PagesCMS since no time-only field'
            required: false
          - name: date_extra
            label: Date extra text
            type: string
            description: Text to display between the date and the address. Use for comments about the concert itself
            required: false
          - name: time_extra
            label: Time extra text
            type: string
            description: Text to display after the time. Use for pre-concert or time notes
            required: false
          - name: location
            type: reference
            options:
              collection: locations
              value: "{short}"
              label: "{title}"
          - name: short
            label: Short display string
            type: string
            required: true
            description: Used for YouTube video links. (ie May 2 Greeley)
          - name: playlist_id
            label: YouTube Playlist
            type: string
            description: Playlist of this specific date. WIP will add to concert page
            required: false
      - name: selections
        label: Music Selections
        type: object
        required: false
        list:
          collapsible:
            collapsed: true
            summary: '{subtitle} | {song}'
        fields:
          - name: subtitle
            label: Subtitle
            description: Concert-specific subtitle (Wonder)
            type: string
            required: false
          - name: song
            label: Song
            type: reference
            options:
              collection: repertoire
              value: '{fields.slug}'
              label: '{fields.title}'
            required: true
            # Skipping instrumentalists and videos, since there's no Key-Value option
            # Would need to switch to object list
      - name: body
        label: Concert Description
        type: rich-text
        required: false
