baseURL = 'https://www.bellsoftherockies.org/'
locale = 'en-us'
title = 'Bells of the Rockies'

[privacy]
[privacy.youtube]
privacyEnhanced = true

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true
