baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/gohugo-ananke/ananke/v2'
